### ISSUE TITLE
Debug order processor

### ISSUE THREAD

**Issue by gitpaulsmith** [alphamatic/amp#1962]
`https://github.com/alphamatic/amp/blob/master/oms/test/test_mr_market.py` is currently disabled because it fails

**Comment by gpsaggese** [comment]
I believe the problem was that we added the infinite loop in the `OrderProcessor` but we didn't set properly the termination condition, so one order was going through correctly and then the `OrderProcessor` was timing out waiting for an order that was not supposed to ever arrive.

I'll do a PR with this + some more instrumentation for easing the debug.

**Comment by gpsaggese** [comment]
Close
